name: "test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test-password:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
      - name: get azure credential
        id: credential
        uses: ./
        with:
          secret: ${{ secrets.Azure_Credential }}
      - run: |
          echo App ID: ${{ steps.credential.outputs.app-id }}
          echo Display Name: ${{ steps.credential.outputs.display-name }}
          echo Tenant: ${{ steps.credential.outputs.tenant }}
          echo Password: ${{ steps.credential.outputs.password }}
      
    