name: "test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test-password:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get azure credential
        id: credential
        uses: ./
        with:
          secret: ${{ secrets.Azure_Credential }}
      - run: echo ${{ steps.credential.outputs.password }}
    